spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ml_feue?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: "070310"
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true